name: Multi-Deploy to Heroku

on: workflow_dispatch

jobs:
  heroku-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY_1}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_1}}
          heroku_email: ${{secrets.HEROKU_EMAIL_1}}
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "us"
        env:
          HD_CONFIG_FILE_URL: ${{secrets.CONFIG_FILE_URL_1}}


  heroku-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY_2}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_2}}
          heroku_email: ${{secrets.HEROKU_EMAIL_2}}
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "us"
        env:
          HD_CONFIG_FILE_URL: ${{secrets.CONFIG_FILE_URL_2}}

  heroku-3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY_3}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_3}}
          heroku_email: ${{secrets.HEROKU_EMAIL_3}}
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "us"
        env:
          HD_CONFIG_FILE_URL: ${{secrets.CONFIG_FILE_URL_3}}
